# Generated by Django 3.1.7 on 2021-03-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_Details',
        ),
    ]
