# Generated by Django 3.0.1 on 2020-12-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='Default Value', max_length=50),
        ),
    ]
