# Generated by Django 3.0.1 on 2020-12-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loginsystem', '0002_users_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Clients',
        ),
    ]
